<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CyntecMESEquipment">
      <HintPath>..\CyntecMESEquipment\bin\Debug\net40\CyntecMESEquipment.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\SampleCode\Sample\bin\Debug\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Services" />
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.12" />
  </ItemGroup>

</Project>
